// Recetario Premium Renacer™ — Comidas (36 recetas)
module.exports = [
  { t:"Pechuga de pollo a la plancha con ensalada de nopales", f:"Fases 1-3",
    i:["1 pechuga de pollo (150 g) sin piel","1 taza de nopal cocido en cubos","1/2 jitomate","1/4 de cebolla morada","Cilantro, limón y sal moderada"],
    p:["Sazona y cocina la pechuga a la plancha 5-6 minutos por lado.","Mezcla el nopal con jitomate, cebolla y cilantro para la ensalada.","Sirve la pechuga rebanada sobre la ensalada, con limón al gusto."],
    c:"Deja reposar el pollo 3 minutos antes de rebanarlo para que no pierda jugosidad." },
  { t:"Pescado blanco al vapor con calabacitas y limón", f:"Fases 1-3",
    i:["200 g de filete de pescado blanco","2 calabacitas en rodajas","Limón, ajo picado y perejil","Sal moderada"],
    p:["Coloca el pescado y las calabacitas en una vaporera.","Cocina 8-10 minutos hasta que el pescado esté opaco.","Sirve con limón, ajo picado y perejil por encima."],
    c:"El pescado blanco (tilapia, mero) es proteína magra con muy poca grasa saturada." },
  { t:"Tinga de pollo baja en sodio con tortillas", f:"Fases 2-3",
    i:["200 g de pechuga de pollo cocida y deshebrada","2 jitomates","1/4 de cebolla","1 chile chipotle (usar con moderación por el sodio)","Tortillas de maíz"],
    p:["Licúa jitomate con muy poco chipotle.","Sofríe la cebolla, agrega la salsa y el pollo deshebrado.","Cocina 8 minutos a fuego bajo y sirve con tortillas calientes."],
    c:"Usa medio chipotle en vez de uno entero para mantener el sodio bajo control." },
  { t:"Lentejas guisadas con verduras y comino", f:"Fases 1-3",
    i:["1 taza de lentejas cocidas","1/2 taza de zanahoria en cubos","1/2 taza de calabaza en cubos","Comino, ajo y cebolla al gusto"],
    p:["Sofríe cebolla y ajo, agrega comino.","Incorpora zanahoria y calabaza, cocina 5 minutos.","Añade las lentejas cocidas con un poco de caldo y cocina 10 minutos más."],
    c:"Las lentejas aportan proteína vegetal y fibra que ayuda al control de glucosa." },
  { t:"Filete de pescado a la veracruzana ligera", f:"Fases 1-3",
    i:["200 g de filete de pescado blanco","1 jitomate picado","Aceitunas y alcaparras (cantidad moderada por el sodio)","1/4 de cebolla","Ajo y laurel"],
    p:["Sofríe cebolla y ajo, agrega el jitomate y cocina 5 minutos.","Añade aceitunas, alcaparras y laurel en cantidad moderada.","Coloca el pescado en la salsa y cocina tapado 10 minutos a fuego bajo."],
    c:"Reduce la cantidad tradicional de aceitunas y alcaparras para cuidar el sodio sin perder el sabor característico." },
  { t:"Pollo a la mexicana con arroz integral", f:"Fases 2-3",
    i:["1 pechuga de pollo en cubos","1 jitomate, 1/4 de cebolla, 1 chile serrano picados","1/2 taza de arroz integral cocido"],
    p:["Sofríe cebolla, chile y jitomate.","Agrega el pollo en cubos y cocina hasta que esté bien cocido.","Sirve sobre una porción pequeña de arroz integral."],
    c:"El arroz integral se digiere más lento que el blanco, ayudando a mantener glucosa estable." },
  { t:"Ensalada César ligera con pollo asado", f:"Fases 1-3",
    i:["1 pechuga de pollo asada en tiras","Lechuga romana","Aderezo: yogur natural, limón, ajo, mostaza y un toque de queso parmesano","Crutones integrales opcionales"],
    p:["Mezcla el yogur con limón, ajo y mostaza para el aderezo.","Coloca la lechuga en un tazón y agrega el aderezo.","Corona con el pollo asado y queso parmesano al gusto."],
    c:"El aderezo con yogur reemplaza la mayonesa tradicional, con menos grasa saturada." },
  { t:"Camarones al ajillo con ejotes salteados", f:"Fases 1-3",
    i:["200 g de camarón limpio","3 dientes de ajo fileteados","1 taza de ejotes","Aceite de oliva y chile de árbol al gusto"],
    p:["Saltea el ajo en poco aceite de oliva hasta dorar ligeramente.","Agrega los camarones y cocina 3-4 minutos.","Sirve sobre los ejotes previamente salteados o al vapor."],
    c:"No sobrecocines el camarón, se pone chicloso después de 4-5 minutos." },
  { t:"Milanesa de pollo al horno con ensalada", f:"Fases 1-3",
    i:["1 pechuga de pollo fileteada","1 huevo","Pan molido integral","Ensalada verde mixta para acompañar"],
    p:["Empaniza la pechuga pasándola por huevo y pan molido integral.","Hornea a 200°C por 20 minutos, volteando a la mitad.","Sirve con ensalada verde fresca."],
    c:"Hornear en vez de freír reduce significativamente la grasa de la receta tradicional." },
  { t:"Picadillo de res magra con verduras", f:"Fases 1-3",
    i:["200 g de carne molida de res magra","1/2 taza de zanahoria en cubos","1/2 taza de calabaza en cubos","Jitomate, cebolla y ajo"],
    p:["Sofríe cebolla y ajo, agrega el jitomate.","Incorpora la carne molida y cocina hasta dorar, retirando el exceso de grasa.","Añade zanahoria y calabaza, cocina tapado 10 minutos."],
    c:"Escurre la grasa que suelte la carne antes de continuar la cocción." },
  { t:"Chile relleno de queso panela al horno", f:"Fases 1-3",
    i:["2 chiles poblanos asados y pelados","60 g de queso panela por chile","Caldillo de jitomate casero"],
    p:["Rellena cada chile con queso panela.","Coloca en refractario y hornea a 180°C 10-12 minutos hasta derretir el queso.","Sirve bañado con caldillo de jitomate caliente."],
    c:"Al hornear en vez de capear y freír, se elimina el aceite de la fritura sin perder el sabor del chile relleno." },
  { t:"Sopa de lentejas con verduras", f:"Fases 1-3",
    i:["1 taza de lentejas","1 zanahoria, 1 papa pequeña o calabaza, 1/2 cebolla","Ajo, laurel y comino"],
    p:["Sofríe cebolla y ajo, agrega las lentejas y el agua o caldo de verduras.","Incorpora las verduras picadas.","Cocina a fuego medio 25-30 minutos hasta que todo esté suave."],
    c:"Prepara una olla grande el domingo — se conserva bien 4-5 días refrigerada." },
  { t:"Ensalada de atún con aguacate y verduras", f:"Fases 1-3",
    i:["1 lata de atún en agua, escurrido","1/4 de aguacate","Jitomate, pepino y cebolla morada picados","Limón y aceite de oliva"],
    p:["Mezcla el atún escurrido con las verduras picadas.","Agrega el aguacate en cubos.","Sazona con limón, un chorrito de aceite de oliva y sal moderada."],
    c:"Elige atún en agua, no en aceite, para controlar mejor la grasa total." },
  { t:"Fajitas de pollo con pimientos y cebolla", f:"Fases 2-3",
    i:["1 pechuga de pollo en tiras","1 pimiento rojo y 1 verde en tiras","1/2 cebolla en tiras","Tortillas integrales"],
    p:["Saltea el pollo hasta dorar y cocer bien.","Agrega los pimientos y la cebolla, cocina 5 minutos más.","Sirve caliente con tortillas integrales."],
    c:"Corta todos los ingredientes del mismo grosor para que se cocinen parejo." },
  { t:"Pescado a la plancha con salsa de mango", f:"Fases 2-3",
    i:["200 g de filete de pescado blanco","1/2 mango maduro en cubos","1/4 de cebolla morada picada","Cilantro y limón"],
    p:["Cocina el pescado a la plancha 4-5 minutos por lado.","Mezcla el mango con cebolla, cilantro y limón para la salsa.","Sirve el pescado bañado con la salsa fresca de mango."],
    c:"La fruta siempre acompañada de proteína (como en esta receta) es la regla de Fase 2-3." },
  { t:"Albóndigas de pavo en caldillo de jitomate", f:"Fases 1-3",
    i:["250 g de pavo molido","1 huevo, pan molido integral, hierbas de olor","Caldillo de jitomate casero con zanahoria y calabaza"],
    p:["Mezcla el pavo con huevo, pan molido y hierbas; forma bolitas.","Cocina el caldillo de jitomate con las verduras.","Agrega las albóndigas al caldillo y cocina 15 minutos a fuego medio."],
    c:"El pavo molido es más magro que la res molida tradicional." },
  { t:"Coliflor arroz con pollo y verduras salteadas", f:"Fases 1-3",
    i:["2 tazas de coliflor rallada tipo arroz","1 pechuga de pollo en cubos","Verduras mixtas (pimiento, zanahoria, chícharo)"],
    p:["Saltea el pollo hasta dorar bien.","En otro sartén, saltea la coliflor rallada 5 minutos.","Mezcla todo con las verduras salteadas y sirve caliente."],
    c:"La coliflor tipo arroz reduce mucho el carbohidrato comparado con arroz normal." },
  { t:"Tacos de pescado empapelado con col morada", f:"Fases 1-3",
    i:["200 g de filete de pescado","Col morada rallada","Limón, chile en polvo","Tortillas de maíz"],
    p:["Envuelve el pescado sazonado en papel aluminio con limón.","Hornea o cocina en sartén tapado 10 minutos.","Sirve desmenuzado en tortillas con col morada y más limón."],
    c:"Cocinar 'empapelado' mantiene el pescado jugoso sin necesidad de aceite extra." },
  { t:"Garbanzos guisados con espinaca y jitomate", f:"Fases 1-3",
    i:["1 1/2 taza de garbanzo cocido","2 tazas de espinaca","1 jitomate picado","Ajo, comino y cebolla"],
    p:["Sofríe cebolla y ajo, agrega el jitomate y el comino.","Incorpora el garbanzo cocido y un poco de caldo.","Añade la espinaca al final y cocina hasta que reduzca."],
    c:"Este platillo funciona igual de bien como comida vegetariana completa." },
  { t:"Pollo al horno con hierbas y verduras asadas", f:"Fases 1-3",
    i:["1 pechuga o pierna de pollo sin piel","Romero, tomillo y ajo","Calabacita, pimiento y cebolla en trozos"],
    p:["Sazona el pollo con las hierbas y ajo.","Coloca en una charola junto con las verduras.","Hornea a 190°C por 30-35 minutos hasta que el pollo esté bien cocido."],
    c:"Cortar las verduras del mismo tamaño asegura que se cuezan parejo con el pollo." },
  { t:"Ensalada de garbanzo, pepino y queso feta", f:"Fases 1-3",
    i:["1 taza de garbanzo cocido","1 pepino en cubos","30 g de queso feta desmoronado","Aceite de oliva, limón y orégano"],
    p:["Mezcla garbanzo y pepino en un tazón.","Agrega el queso feta desmoronado.","Sazona con aceite de oliva, limón y orégano."],
    c:"El queso feta tiene sabor intenso, así que un poco rinde bastante." },
  { t:"Filete de res magra a la parrilla con ensalada verde", f:"Fases 1-3",
    i:["150 g de filete de res magro","Lechuga, jitomate, pepino","Aceite de oliva y limón"],
    p:["Sazona el filete y cocina a la parrilla al término deseado.","Prepara la ensalada verde con aceite de oliva y limón.","Deja reposar la carne 3 minutos antes de servir."],
    c:"Elige cortes magros como filete o arrachera desgrasada." },
  { t:"Estofado de pollo con verduras de raíz", f:"Fases 2-3",
    i:["1 pechuga o pierna de pollo","1 zanahoria, 1 camote pequeño, 1 papa pequeña","Caldo de pollo casero bajo en sodio"],
    p:["Sella el pollo en un sartén con poco aceite.","Agrega las verduras de raíz cortadas en trozos y el caldo.","Cocina tapado a fuego bajo 25-30 minutos hasta que todo esté suave."],
    c:"El camote es un carbohidrato complejo apropiado a partir de Fase 2." },
  { t:"Camarones a la diabla baja en sodio con ensalada", f:"Fases 1-3",
    i:["200 g de camarón limpio","2 chiles guajillo hidratados (usar con moderación por el sodio de conservas)","Ajo y cebolla","Ensalada verde para acompañar"],
    p:["Licúa el chile guajillo con ajo y un poco de agua.","Saltea la cebolla, agrega la salsa y cocina 3 minutos.","Añade los camarones y cocina 4 minutos; sirve con ensalada."],
    c:"Prepara tu propia salsa de chile en vez de usar salsas embotelladas para controlar el sodio." },
  { t:"Tacos de coliflor asada con salsa verde", f:"Fases 1-3",
    i:["2 tazas de coliflor en floretes","Especias: comino, pimentón, ajo en polvo","Tortillas de maíz y salsa verde"],
    p:["Sazona la coliflor con las especias y un toque de aceite.","Hornea a 200°C por 20-25 minutos hasta dorar.","Sirve en tortillas con salsa verde."],
    c:"Opción vegetariana con textura similar a los tacos de carne asada." },
  { t:"Ensalada de quinoa con verduras y pollo desmenuzado", f:"Fases 2-3",
    i:["1/2 taza de quinoa cocida","100 g de pollo cocido desmenuzado","Pepino, jitomate y pimiento picados","Aceite de oliva y limón"],
    p:["Mezcla la quinoa fría con las verduras picadas.","Agrega el pollo desmenuzado.","Sazona con aceite de oliva, limón y sal moderada."],
    c:"Cocina la quinoa con anticipación y refrigérala para armar esta ensalada en minutos." },
  { t:"Caldo tlalpeño de pollo bajo en sodio", f:"Fases 1-3",
    i:["1 pechuga de pollo cocida y deshebrada","1/2 taza de garbanzo cocido","1 zanahoria y 1 calabacita","Chile chipotle en cantidad mínima","Aguacate para servir"],
    p:["Cocina el caldo con la pechuga, zanahoria y calabacita.","Agrega el garbanzo y un toque mínimo de chipotle.","Sirve con aguacate en cubos encima."],
    c:"Un solo chipotle chico (o incluso solo un poco de su salsa) es suficiente para dar el sabor característico." },
  { t:"Berenjena rellena de picadillo de pavo", f:"Fases 1-3",
    i:["1 berenjena grande partida a la mitad","150 g de pavo molido","Jitomate, cebolla y ajo picados","Queso panela rallado (opcional)"],
    p:["Ahueca la berenjena y pica la pulpa retirada.","Sofríe cebolla, ajo, jitomate, la pulpa de berenjena y el pavo molido.","Rellena las mitades de berenjena y hornea a 190°C 20 minutos."],
    c:"Puedes gratinar con un poco de queso panela los últimos 5 minutos de horneado." },
  { t:"Salmón al horno con espárragos", f:"Fases 1-3",
    i:["200 g de filete de salmón","1 taza de espárragos","Limón, eneldo y ajo"],
    p:["Coloca el salmón y los espárragos en una charola.","Sazona con limón, eneldo y ajo.","Hornea a 200°C por 12-15 minutos."],
    c:"El salmón aporta grasas saludables omega-3, buenas para la salud cardiovascular." },
  { t:"Nopales asados con queso panela y ensalada", f:"Fases 1-3",
    i:["4 nopales enteros asados","60 g de queso panela","Ensalada de jitomate y cebolla"],
    p:["Asa los nopales enteros en comal o parrilla hasta suavizar.","Corta en tiras y coloca el queso panela encima para que se derrita con el calor.","Sirve con la ensalada de jitomate y cebolla."],
    c:"Asar el nopal entero (no cortado) evita que suelte tanta baba al cocinarse." },
  { t:"Pechuga rellena de espinaca y queso panela", f:"Fases 1-3",
    i:["1 pechuga de pollo grande, abierta tipo mariposa","1 taza de espinaca salteada","40 g de queso panela"],
    p:["Rellena la pechuga abierta con la espinaca y el queso panela.","Cierra con palillos y sella en sartén por ambos lados.","Termina la cocción en horno a 190°C por 15-18 minutos."],
    c:"Sellar antes de hornear ayuda a que la pechuga quede jugosa por dentro." },
  { t:"Tostadas de atún con verduras", f:"Fases 1-3",
    i:["2 tostadas horneadas","1 lata de atún en agua","Pepino, jitomate y cebolla picados","Limón y aceite de oliva"],
    p:["Mezcla el atún escurrido con las verduras picadas.","Sazona con limón y un chorrito de aceite de oliva.","Sirve la mezcla sobre las tostadas horneadas."],
    c:"Arma las tostadas justo antes de comer para que no se humedezcan." },
  { t:"Ensalada de lentejas con verduras asadas", f:"Fases 1-3",
    i:["1 taza de lentejas cocidas","Calabacita y pimiento asados en trozos","Aceite de oliva, vinagre y hierbas"],
    p:["Asa la calabacita y el pimiento hasta que doren ligeramente.","Mezcla con las lentejas cocidas.","Sazona con aceite de oliva, vinagre y hierbas al gusto."],
    c:"Se puede servir tibia o fría, ambas versiones funcionan bien." },
  { t:"Pollo estilo tikka casero al horno con verduras", f:"Fases 1-3",
    i:["1 pechuga de pollo en cubos","1/2 taza de yogur natural","Especias: comino, cúrcuma, pimentón, ajo","Verduras variadas para acompañar"],
    p:["Marina el pollo en el yogur con las especias mínimo 30 minutos.","Coloca en charola junto con las verduras.","Hornea a 200°C por 20-25 minutos."],
    c:"El yogur en la marinada ayuda a que la pechuga quede más suave y jugosa." },
  { t:"Pescado a la plancha con puré de coliflor", f:"Fases 1-3",
    i:["200 g de filete de pescado blanco","2 tazas de coliflor cocida","Un toque de aceite de oliva, ajo y sal moderada"],
    p:["Cocina el pescado a la plancha 4-5 minutos por lado.","Licúa o machaca la coliflor cocida con ajo y aceite de oliva hasta obtener textura de puré.","Sirve el pescado sobre el puré de coliflor."],
    c:"El puré de coliflor es una alternativa con muchos menos carbohidratos que el puré de papa." },
  { t:"Guisado de res magra con nopales y calabacitas", f:"Fases 1-3",
    i:["200 g de carne de res magra en cubos","1 taza de nopal cocido","1 calabacita en cubos","Jitomate, cebolla y ajo"],
    p:["Sella la carne en un sartén con poco aceite.","Agrega cebolla, ajo y jitomate, cocina 5 minutos.","Incorpora nopal y calabacita, tapa y cocina 15-20 minutos a fuego bajo."],
    c:"Cortar la carne en cubos pequeños ayuda a que se cocine más rápido y quede suave." }
];
