// Recetario Premium Renacer™ — Bebidas (36 recetas, todas sin azúcar añadida)
module.exports = [
  { t:"Agua de jamaica sin azúcar", f:"Fases 1-3",
    i:["1 taza de flor de jamaica seca","1 litro de agua","Stevia al gusto (opcional)"],
    p:["Hierve la jamaica en el agua 10 minutos.","Deja enfriar y cuela.","Endulza con stevia si lo deseas, nunca con azúcar."],
    c:"La jamaica sin azúcar es naturalmente ácida — pruébala antes de endulzar, a veces no hace falta." },
  { t:"Agua de pepino con limón y menta", f:"Fases 1-3",
    i:["1 pepino en rodajas","1 limón en rodajas","Hojas de menta","1 litro de agua"],
    p:["Coloca todos los ingredientes en una jarra.","Refrigera mínimo 1 hora para que suelten sabor.","Sirve fría."],
    c:"Se puede rellenar la jarra de agua 2-3 veces con los mismos ingredientes antes de renovarlos." },
  { t:"Té verde con jengibre", f:"Fases 1-3",
    i:["1 bolsita o cucharadita de té verde","1 rodaja de jengibre fresco","Agua caliente"],
    p:["Hierve el jengibre en el agua 5 minutos.","Retira del fuego y agrega el té verde, deja reposar 3 minutos.","Cuela y sirve."],
    c:"No dejes reposar el té verde más de 3-4 minutos o se vuelve amargo." },
  { t:"Licuado verde de espinaca, manzana y limón", f:"Fases 2-3",
    i:["1 taza de espinaca","1/2 manzana verde","Jugo de 1/2 limón","1 taza de agua"],
    p:["Licúa todos los ingredientes hasta obtener consistencia homogénea.","Cuela si prefieres una textura más ligera.","Sirve de inmediato."],
    c:"Tómalo recién preparado — pierde nutrientes y sabor si se guarda varias horas." },
  { t:"Agua de limón con chía", f:"Fases 1-3",
    i:["Jugo de 2 limones","1 cucharada de chía","1 litro de agua","Stevia al gusto (opcional)"],
    p:["Mezcla el jugo de limón con el agua.","Agrega la chía y deja reposar 10 minutos para que gelifique.","Sirve fría."],
    c:"La chía se hidrata y aumenta ligeramente la textura del agua — es normal." },
  { t:"Infusión de manzanilla", f:"Fases 1-3",
    i:["1 cucharadita de flor de manzanilla seca","Agua caliente"],
    p:["Vierte agua caliente sobre la manzanilla.","Deja reposar 5 minutos.","Cuela y sirve."],
    c:"Buena opción por la noche por su efecto relajante suave." },
  { t:"Té de canela sin azúcar", f:"Fases 1-3",
    i:["1 raja de canela","2 tazas de agua"],
    p:["Hierve la canela en el agua 10 minutos.","Deja reposar 5 minutos más.","Sirve caliente o fría."],
    c:"Algunos estudios sugieren que la canela puede ayudar a la sensibilidad a la insulina — de cualquier forma, nunca sustituye tratamiento médico." },
  { t:"Agua de tamarindo sin azúcar", f:"Fases 1-3",
    i:["8-10 vainas de tamarindo sin cáscara","1 litro de agua","Stevia al gusto (opcional)"],
    p:["Remoja el tamarindo en agua caliente 15 minutos.","Machaca y cuela la pulpa.","Diluye con más agua y endulza con stevia si lo deseas."],
    c:"El tamarindo natural es ácido — la stevia ayuda a balancear el sabor sin azúcar." },
  { t:"Licuado de fresa con yogur natural", f:"Fases 2-3",
    i:["1 taza de fresas","1/2 taza de yogur natural sin azúcar","1/2 taza de agua o hielo"],
    p:["Licúa todos los ingredientes hasta obtener consistencia cremosa.","Ajusta con más agua si prefieres más líquido.","Sirve de inmediato."],
    c:"Funciona también como snack si se toma en un vaso pequeño entre comidas." },
  { t:"Kombucha casera sin azúcar añadida", f:"Fases 2-3",
    i:["Té negro o verde fermentado con SCOBY","Agua","(Requiere cultivo de kombucha y proceso de fermentación de 7-10 días)"],
    p:["Prepara el té y déjalo enfriar por completo.","Agrega el SCOBY y fermenta tapado con tela 7-10 días a temperatura ambiente.","Refrigera para detener la fermentación antes de tomar."],
    c:"El azúcar inicial se usa para alimentar al SCOBY durante la fermentación, no queda en el producto final tras el proceso completo — aun así, introdúcela con moderación al principio." },
  { t:"Agua de melón sin azúcar", f:"Fases 2-3",
    i:["2 tazas de melón en cubos","2 tazas de agua","Hielo al gusto"],
    p:["Licúa el melón con el agua.","Cuela si prefieres una textura más ligera.","Sirve con hielo."],
    c:"El melón ya aporta dulzor natural suficiente, no necesita azúcar extra." },
  { t:"Café negro o con leche de almendra sin azúcar", f:"Fases 1-3",
    i:["1 taza de café preparado","Leche de almendra sin azúcar al gusto (opcional)"],
    p:["Prepara el café de tu método habitual.","Agrega leche de almendra si prefieres un café con leche.","Sirve sin azúcar."],
    c:"Modera el consumo de cafeína si tienes presión arterial alta — consulta con tu médico la cantidad adecuada para ti." },
  { t:"Té de hibisco con menta", f:"Fases 1-3",
    i:["1 cucharada de flor de jamaica","Hojas de menta fresca","Agua caliente"],
    p:["Hierve la jamaica 8 minutos.","Agrega las hojas de menta al final y deja reposar 2 minutos más.","Cuela y sirve."],
    c:"La combinación de jamaica y menta funciona bien tanto caliente como fría." },
  { t:"Agua de piña con hierbabuena", f:"Fases 2-3",
    i:["1 taza de piña en cubos","Hojas de hierbabuena","1 litro de agua"],
    p:["Licúa la piña con parte del agua.","Cuela y mezcla con el resto del agua.","Agrega hierbabuena fresca y sirve fría."],
    c:"La piña tiene un índice glucémico medio — una porción moderada como bebida está bien en Fase 2-3." },
  { t:"Licuado de aguacate y leche de almendra sin azúcar", f:"Fases 2-3",
    i:["1/4 de aguacate","1 taza de leche de almendra sin azúcar","Canela al gusto"],
    p:["Licúa el aguacate con la leche de almendra.","Agrega canela y licúa unos segundos más.","Sirve frío."],
    c:"Bebida cremosa y saciante gracias a la grasa saludable del aguacate." },
  { t:"Agua de pepino y jengibre", f:"Fases 1-3",
    i:["1 pepino en rodajas","1 rodaja de jengibre fresco","1 litro de agua"],
    p:["Coloca el pepino y el jengibre en una jarra con agua.","Refrigera mínimo 1 hora.","Sirve fría."],
    c:"El jengibre le da un toque picante suave y fresco al agua de pepino." },
  { t:"Té de manzanilla con limón", f:"Fases 1-3",
    i:["1 cucharadita de manzanilla seca","Jugo de 1/2 limón","Agua caliente"],
    p:["Prepara la infusión de manzanilla.","Agrega el jugo de limón antes de servir.","Toma caliente o tibia."],
    c:"El limón puede ayudar a suavizar el sabor herbal de la manzanilla." },
  { t:"Infusión de romero", f:"Fases 1-3",
    i:["1 ramita de romero fresco","Agua caliente"],
    p:["Vierte agua caliente sobre el romero.","Deja reposar 5 minutos.","Cuela y sirve."],
    c:"El romero tiene un sabor intenso — usa solo una ramita pequeña por taza." },
  { t:"Agua fresca de sandía", f:"Fases 2-3",
    i:["2 tazas de sandía en cubos","2 tazas de agua","Hielo al gusto"],
    p:["Licúa la sandía con el agua.","Cuela si prefieres textura más ligera.","Sirve con hielo."],
    c:"La sandía tiene índice glucémico alto — toma solo una porción moderada, mejor acompañada de otros alimentos." },
  { t:"Té negro con canela", f:"Fases 1-3",
    i:["1 bolsita de té negro","1 raja de canela pequeña","Agua caliente"],
    p:["Hierve la canela en el agua 5 minutos.","Agrega el té negro y deja reposar 3 minutos.","Cuela y sirve."],
    c:"Modera el consumo si eres sensible a la cafeína por la tarde-noche." },
  { t:"Agua de arándano sin azúcar", f:"Fases 2-3",
    i:["1 taza de arándanos","1 litro de agua","Stevia al gusto (opcional)"],
    p:["Machaca ligeramente los arándanos.","Mezcla con el agua y deja reposar 20 minutos en refrigeración.","Cuela si lo prefieres y sirve fría."],
    c:"Los arándanos son de los frutos con menor impacto glucémico entre las frutas." },
  { t:"Licuado de plátano y avena", f:"Fases 2-3",
    i:["1/2 plátano","2 cucharadas de avena","1 taza de leche vegetal sin azúcar","Canela al gusto"],
    p:["Licúa todos los ingredientes hasta que la avena se integre bien.","Deja reposar 5 minutos para que espese ligeramente.","Sirve frío."],
    c:"Bebida más completa, funciona bien como parte de un desayuno rápido." },
  { t:"Kéfir de agua con limón", f:"Fases 1-3",
    i:["1 taza de kéfir de agua fermentado","Jugo de limón al gusto"],
    p:["Prepara o adquiere el kéfir de agua ya fermentado.","Agrega jugo de limón al gusto.","Sirve frío."],
    c:"El kéfir de agua es otra fuente de probióticos, alternativa si no consumes lácteos." },
  { t:"Agua de toronja sin azúcar", f:"Fases 1-3",
    i:["1 toronja en jugo","1 litro de agua","Hielo al gusto"],
    p:["Exprime la toronja.","Mezcla el jugo con el agua.","Sirve con hielo, sin azúcar añadida."],
    c:"La toronja puede interactuar con algunos medicamentos — Edgar debe confirmar con el médico de cada alumno antes de recomendarla en casos con medicación." },
  { t:"Té de jamaica con jengibre", f:"Fases 1-3",
    i:["1 cucharada de flor de jamaica","1 rodaja de jengibre","Agua caliente"],
    p:["Hierve la jamaica y el jengibre juntos 8-10 minutos.","Cuela y sirve caliente o deja enfriar."],
    c:"Combina bien el efecto refrescante de la jamaica con el toque picante del jengibre." },
  { t:"Infusión de menta fresca", f:"Fases 1-3",
    i:["Hojas de menta fresca","Agua caliente"],
    p:["Vierte agua caliente sobre las hojas de menta.","Deja reposar 5 minutos.","Cuela y sirve."],
    c:"Ayuda a la digestión después de una comida pesada." },
  { t:"Agua de coco natural", f:"Fases 1-3",
    i:["1 coco fresco o agua de coco 100% natural sin azúcar añadida"],
    p:["Abre el coco y sirve el agua directamente, o vierte el agua de coco natural en un vaso con hielo."],
    c:"Verifica siempre la etiqueta si compras agua de coco embotellada — que no tenga azúcar añadida." },
  { t:"Licuado de espinaca, piña y chía", f:"Fases 2-3",
    i:["1 taza de espinaca","1/2 taza de piña en cubos","1 cucharada de chía","1 taza de agua"],
    p:["Licúa todos los ingredientes hasta integrar bien.","Deja reposar unos minutos si quieres que la chía espese un poco la bebida.","Sirve frío."],
    c:"La piña aporta el dulzor natural que hace más agradable el sabor de la espinaca." },
  { t:"Té chai casero sin azúcar", f:"Fases 1-3",
    i:["1 bolsita de té negro","Canela, cardamomo, jengibre y clavo al gusto","Leche vegetal sin azúcar (opcional)"],
    p:["Hierve las especias en agua 5-8 minutos.","Agrega el té negro y deja reposar 3 minutos más.","Cuela, agrega leche vegetal si lo deseas, y sirve caliente."],
    c:"Ajusta la cantidad de especias a tu gusto — el chai tradicional es intenso en sabor." },
  { t:"Agua de pepino, limón y menta fría", f:"Fases 1-3",
    i:["1 pepino en rodajas","1 limón en rodajas","Hojas de menta","Hielo abundante"],
    p:["Combina todos los ingredientes en una jarra con hielo.","Deja reposar 15-20 minutos antes de servir.","Sirve bien fría."],
    c:"Ideal para tener siempre lista en el refrigerador durante el día." },
  { t:"Café de olla sin azúcar con canela", f:"Fases 1-3",
    i:["Café de grano molido","1 raja de canela","Agua"],
    p:["Hierve el agua con la canela 5 minutos.","Agrega el café molido y cocina 3-4 minutos más sin hervir con fuerza.","Cuela y sirve caliente, sin piloncillo."],
    c:"La canela sustituye parte del dulzor que tradicionalmente aporta el piloncillo." },
  { t:"Agua de fresa con albahaca", f:"Fases 2-3",
    i:["1 taza de fresas rebanadas","Hojas de albahaca","1 litro de agua"],
    p:["Machaca ligeramente las fresas.","Combina con el agua y la albahaca en una jarra.","Refrigera 30 minutos antes de servir."],
    c:"La albahaca da un toque aromático distinto al típico de menta o hierbabuena." },
  { t:"Té verde con limón", f:"Fases 1-3",
    i:["1 bolsita de té verde","Jugo de 1/2 limón","Agua caliente"],
    p:["Prepara el té verde dejándolo reposar 3 minutos.","Agrega el jugo de limón.","Sirve caliente o frío con hielo."],
    c:"El té verde frío con limón es una buena alternativa al refresco en el calor." },
  { t:"Licuado de yogur, fresa y linaza", f:"Fases 2-3",
    i:["1/2 taza de yogur natural sin azúcar","1/2 taza de fresas","1 cucharada de linaza molida","Agua o hielo al gusto"],
    p:["Licúa todos los ingredientes hasta obtener consistencia cremosa.","Ajusta con agua si prefieres más líquido.","Sirve de inmediato."],
    c:"Bebida completa, funciona bien como snack en vaso pequeño." },
  { t:"Infusión de jengibre y limón", f:"Fases 1-3",
    i:["1 rodaja de jengibre fresco","Jugo de 1/2 limón","Agua caliente"],
    p:["Hierve el jengibre 5-8 minutos.","Agrega el jugo de limón antes de servir.","Toma caliente."],
    c:"Buena opción para las mañanas frías o cuando se busca algo digestivo." },
  { t:"Agua de flor de jamaica con canela", f:"Fases 1-3",
    i:["1 cucharada de flor de jamaica","1 raja de canela","1 litro de agua","Stevia al gusto (opcional)"],
    p:["Hierve la jamaica y la canela juntas 10 minutos.","Deja enfriar y cuela.","Endulza con stevia si lo deseas y sirve fría."],
    c:"La canela le da un toque cálido distinto al agua de jamaica tradicional." }
];
