// Recetario Premium Renacer™ — Snacks (36 recetas, porciones pequeñas entre comidas)
module.exports = [
  { t:"Puño de almendras y nueces", f:"Fases 1-3",
    i:["10-12 almendras","5-6 mitades de nuez"],
    p:["Mide la porción con la mano (un puño) para no pasarte de cantidad.","Come despacio, sin acompañar con pantalla para notar la saciedad."],
    c:"Las grasas de la nuez ayudan a sostener el hambre entre comidas sin picos de glucosa." },
  { t:"Palitos de jícama con limón y chile piquín", f:"Fases 1-3",
    i:["1 taza de jícama en bastones","Limón al gusto","Chile piquín sin azúcar añadida"],
    p:["Corta la jícama en bastones.","Exprime limón encima.","Espolvorea chile piquín justo antes de comer."],
    c:"Revisa la etiqueta del chile en polvo — muchas marcas comerciales llevan azúcar oculta." },
  { t:"Hummus de garbanzo con verduras", f:"Fases 1-3",
    i:["1 taza de garbanzo cocido","1 diente de ajo, jugo de limón, aceite de oliva","Zanahoria y apio en bastones para acompañar"],
    p:["Licúa el garbanzo con ajo, limón y aceite de oliva hasta obtener una pasta.","Ajusta consistencia con un poco de agua si es necesario.","Sirve con bastones de verdura para untar."],
    c:"Prepara un lote grande de hummus — se conserva refrigerado hasta 5 días." },
  { t:"Huevo cocido con sal de mar", f:"Fases 1-3",
    i:["1-2 huevos cocidos","Sal de mar en cantidad mínima","Pimienta al gusto"],
    p:["Cuece los huevos 9-10 minutos para que la yema quede firme.","Pela y corta a la mitad.","Sazona con una pizca de sal y pimienta."],
    c:"Cuece varios huevos el domingo para tener este snack listo toda la semana." },
  { t:"Yogur natural con canela", f:"Fases 1-3",
    i:["1 taza de yogur natural sin azúcar","Canela al gusto"],
    p:["Sirve el yogur en un tazón pequeño.","Espolvorea canela encima."],
    c:"La canela aporta un toque de dulzor natural sin necesidad de azúcar." },
  { t:"Rodajas de pepino con queso panela", f:"Fases 1-3",
    i:["1 pepino en rodajas","30 g de queso panela en cubos pequeños"],
    p:["Corta el pepino en rodajas.","Coloca un cubito de queso panela sobre cada rodaja."],
    c:"Snack fresco y crujiente, ideal para climas calurosos." },
  { t:"Manzana verde con crema de almendra", f:"Fases 2-3",
    i:["1/2 manzana verde en rebanadas","1 cucharada de crema de almendra sin azúcar añadida"],
    p:["Rebana la manzana en gajos.","Sirve con la crema de almendra para untar."],
    c:"En Fase 1 sustituye la manzana por apio en bastones con la misma crema de almendra." },
  { t:"Edamame al vapor con sal", f:"Fases 1-3",
    i:["1 taza de edamame con vaina","Sal de mar en cantidad mínima"],
    p:["Cocina el edamame al vapor o hervido 5 minutos.","Escurre y espolvorea con una pizca de sal."],
    c:"Buena fuente de proteína vegetal para media tarde." },
  { t:"Chips de nopal horneados", f:"Fases 1-3",
    i:["2 nopales cortados en tiras delgadas","Sal y limón al gusto"],
    p:["Coloca las tiras de nopal en una charola con papel para hornear.","Hornea a 150°C por 30-40 minutos hasta que sequen y estén crujientes.","Sazona con sal y limón antes de servir."],
    c:"Deben quedar completamente secos para lograr la textura crujiente de un chip." },
  { t:"Palomitas naturales al aire", f:"Fases 2-3",
    i:["1/4 taza de maíz palomero","Sal moderada"],
    p:["Cocina el maíz en una olla tapada sin aceite (a fuego medio, moviendo ocasionalmente) o en máquina de aire.","Espera a que dejen de tronar.","Sazona con una pizca de sal, sin mantequilla."],
    c:"Evita las versiones de microondas comerciales — suelen llevar grasas y sodio en exceso." },
  { t:"Zanahoria baby con hummus", f:"Fases 1-3",
    i:["1 taza de zanahoria baby","3 cucharadas de hummus casero"],
    p:["Lava bien las zanahorias.","Sirve con el hummus para acompañar."],
    c:"Snack práctico para llevar en un contenedor pequeño fuera de casa." },
  { t:"Té helado sin azúcar con menta", f:"Fases 1-3",
    i:["1 taza de té negro o verde frío","Hojas de menta fresca","Hielo al gusto"],
    p:["Prepara el té y déjalo enfriar.","Agrega hielo y hojas de menta.","Sirve como acompañante de un snack sólido."],
    c:"Sirve como bebida de acompañamiento, no reemplaza al snack sólido." },
  { t:"Queso panela en cubos con jitomate cherry", f:"Fases 1-3",
    i:["40 g de queso panela en cubos","6-8 jitomates cherry","Orégano al gusto"],
    p:["Corta el queso panela en cubos.","Alterna con los jitomates cherry en un plato pequeño o palillo.","Espolvorea orégano."],
    c:"Fácil de armar como snack para llevar al trabajo en un contenedor pequeño." },
  { t:"Mix de semillas tostadas", f:"Fases 1-3",
    i:["2 cucharadas de semilla de calabaza","2 cucharadas de semilla de girasol","Sal en cantidad mínima"],
    p:["Tuesta las semillas en sartén seco a fuego medio, moviendo constantemente.","Retira cuando doren ligeramente.","Sazona con una pizca de sal."],
    c:"Tostar las semillas resalta su sabor sin necesidad de aceite." },
  { t:"Rollitos de jamón de pavo con queso panela", f:"Fases 1-3",
    i:["3-4 rebanadas de jamón de pavo bajo en sodio","30 g de queso panela en tiras"],
    p:["Coloca una tira de queso panela sobre cada rebanada de jamón.","Enrolla y asegura con un palillo si es necesario."],
    c:"Busca jamón de pavo con la menor cantidad de sodio y sin nitritos añadidos que encuentres." },
  { t:"Fresas con yogur griego", f:"Fases 2-3",
    i:["1/2 taza de fresas rebanadas","1/2 taza de yogur griego natural sin azúcar"],
    p:["Coloca el yogur en un tazón pequeño.","Agrega las fresas encima."],
    c:"El yogur griego tiene más proteína que el yogur natural regular, aportando mayor saciedad." },
  { t:"Garbanzos rostizados con especias", f:"Fases 1-3",
    i:["1 taza de garbanzo cocido y seco","Comino, pimentón y ajo en polvo","Un toque de aceite de oliva"],
    p:["Mezcla el garbanzo con el toque de aceite y las especias.","Hornea a 200°C por 25-30 minutos, moviendo a la mitad, hasta que doren y crujan.","Deja enfriar antes de comer para que terminen de crujir."],
    c:"Sécalos muy bien con una servilleta antes de hornear para que queden más crujientes." },
  { t:"Apio con crema de cacahuate natural", f:"Fases 2-3",
    i:["2 tallos de apio en bastones","1 cucharada de crema de cacahuate 100% natural, sin azúcar añadida"],
    p:["Corta el apio en bastones.","Unta la crema de cacahuate sobre cada bastón."],
    c:"Revisa que la crema de cacahuate solo tenga cacahuate (y quizá sal) en los ingredientes." },
  { t:"Gelatina sin azúcar de agua de jamaica", f:"Fases 1-3",
    i:["2 tazas de agua de jamaica sin azúcar","Grenetina sin sabor"],
    p:["Hidrata la grenetina según las instrucciones del empaque.","Mezcla con el agua de jamaica caliente hasta disolver bien.","Refrigera en moldes hasta cuajar, mínimo 3 horas."],
    c:"Endulza el agua de jamaica con stevia si buscas un toque más dulce, nunca con azúcar." },
  { t:"Barritas caseras de avena y semillas", f:"Fases 2-3",
    i:["1 1/2 taza de avena","1/3 taza de puré de plátano","2 cucharadas de semillas variadas","Canela al gusto"],
    p:["Mezcla todos los ingredientes hasta integrar.","Extiende en un molde cuadrado y presiona firmemente.","Hornea a 170°C por 20 minutos, deja enfriar y corta en barras."],
    c:"El puré de plátano funciona como aglutinante natural y endulzante, sin azúcar añadida." },
  { t:"Aguacate con limón y sal", f:"Fases 1-3",
    i:["1/2 aguacate","Limón y sal de mar en cantidad mínima"],
    p:["Corta el aguacate a la mitad y retira el hueso.","Exprime limón encima.","Sazona con una pizca de sal y come directo con cuchara."],
    c:"Snack simple con grasa saludable que ayuda a sostener el hambre." },
  { t:"Chicharrón de nopal (nopal deshidratado)", f:"Fases 1-3",
    i:["3 nopales en tiras delgadas","Sal y limón"],
    p:["Sazona las tiras de nopal con sal y limón.","Deshidrata en horno a temperatura baja (100°C) por 1-2 horas hasta que sequen por completo.","Deja enfriar antes de servir para que terminen de crujir."],
    c:"Requiere paciencia pero el resultado es un snack crujiente sin freír nada." },
  { t:"Cubos de melón con jamón serrano", f:"Fases 2-3",
    i:["1 taza de melón en cubos","2-3 rebanadas de jamón serrano en trozos pequeños"],
    p:["Corta el melón en cubos.","Envuelve cada cubo con un trozo pequeño de jamón serrano."],
    c:"El jamón serrano aporta bastante sodio — usa poca cantidad y evítalo si tu presión está elevada esa semana." },
  { t:"Té de jengibre con limón", f:"Fases 1-3",
    i:["1 rodaja de jengibre fresco","Agua caliente","Limón al gusto"],
    p:["Hierve el jengibre en agua 5 minutos.","Cuela y agrega limón al gusto.","Sirve caliente como acompañante de un snack sólido."],
    c:"El jengibre puede ayudar a la digestión entre comidas." },
  { t:"Nueces de la india tostadas", f:"Fases 1-3",
    i:["1 puño de nuez de la india natural","Sal en cantidad mínima"],
    p:["Tuesta las nueces en sartén seco a fuego medio hasta dorar ligeramente.","Sazona con una pizca de sal.","Deja enfriar antes de comer."],
    c:"Evita las versiones saladas o cubiertas de miel que se venden ya preparadas." },
  { t:"Rebanadas de pera con queso cottage", f:"Fases 2-3",
    i:["1/2 pera en rebanadas","1/2 taza de queso cottage"],
    p:["Rebana la pera.","Sirve junto con el queso cottage en un tazón pequeño."],
    c:"El queso cottage aporta proteína que ayuda a moderar el impacto de la fruta." },
  { t:"Pepinillos caseros fermentados", f:"Fases 1-3",
    i:["Pepinos pequeños","Agua, sal y ajo","Eneldo al gusto"],
    p:["Coloca los pepinos enteros en un frasco con ajo y eneldo.","Cubre con salmuera (agua con sal disuelta) y tapa sin cerrar herméticamente.","Deja fermentar a temperatura ambiente 3-5 días, luego refrigera."],
    c:"Es un alimento fermentado que aporta probióticos naturales, parte del pilar de intestino." },
  { t:"Rollitos de lechuga con atún", f:"Fases 1-3",
    i:["Hojas de lechuga","1/2 lata de atún en agua","Limón y sal moderada"],
    p:["Mezcla el atún escurrido con limón y una pizca de sal.","Coloca una cucharada sobre cada hoja de lechuga.","Enrolla y come de inmediato."],
    c:"Snack con buena cantidad de proteína y prácticamente sin carbohidrato." },
  { t:"Chips de calabacita horneados", f:"Fases 1-3",
    i:["2 calabacitas en rodajas muy delgadas","Sal, pimienta y un toque de aceite de oliva en aerosol"],
    p:["Coloca las rodajas en una charola sin encimarlas.","Hornea a 150°C por 40-50 minutos hasta que sequen y doren en los bordes.","Deja enfriar para que terminen de crujir."],
    c:"Corta las rodajas lo más delgado posible para que logren la textura crujiente." },
  { t:"Ciruela pasa con nuez", f:"Fases 2-3",
    i:["2-3 ciruelas pasas sin azúcar añadida","4-5 mitades de nuez"],
    p:["Sirve las ciruelas pasas junto con la nuez en una porción pequeña."],
    c:"Porción controlada — la ciruela pasa, aunque natural, concentra azúcares al deshidratarse." },
  { t:"Yogur con linaza molida", f:"Fases 1-3",
    i:["1 taza de yogur natural sin azúcar","1 cucharada de linaza molida"],
    p:["Sirve el yogur en un tazón.","Espolvorea la linaza recién molida encima."],
    c:"Muele la linaza justo antes de usarla — pierde propiedades si se muele con mucha anticipación." },
  { t:"Palitos de apio y zanahoria con guacamole", f:"Fases 1-3",
    i:["Apio y zanahoria en bastones","1/2 aguacate machacado con limón, sal y cilantro"],
    p:["Prepara el guacamole machacando el aguacate con limón, sal y cilantro.","Sirve con los bastones de verdura para untar."],
    c:"El guacamole simple (sin jitomate ni cebolla) se conserva mejor de un día para otro con limón extra." },
  { t:"Almendras enchiladas sin azúcar", f:"Fases 1-3",
    i:["1 taza de almendra natural","Chile en polvo sin azúcar, limón"],
    p:["Rocía las almendras con un poco de limón.","Espolvorea el chile en polvo y mezcla bien.","Deja secar 10 minutos antes de comer."],
    c:"Revisa que el chile en polvo que uses no tenga azúcar en la lista de ingredientes." },
  { t:"Kéfir natural", f:"Fases 1-3",
    i:["1/2 taza de kéfir natural sin azúcar añadida"],
    p:["Sirve el kéfir en un vaso pequeño.","Toma despacio como snack de media tarde."],
    c:"El kéfir es otro fermentado que suma al pilar de salud intestinal." },
  { t:"Tostada pequeña integral con aguacate", f:"Fases 1-3",
    i:["1 tostada horneada pequeña o media rebanada de pan integral tostado","2 cucharadas de aguacate machacado"],
    p:["Machaca el aguacate con un poco de limón y sal.","Unta sobre la tostada.","Come de inmediato."],
    c:"Versión mini de un desayuno completo, útil como snack de media mañana." },
  { t:"Mix de frutos secos y semillas en porción controlada", f:"Fases 1-3",
    i:["1 cucharada de almendra","1 cucharada de nuez","1 cucharada de semilla de calabaza"],
    p:["Mezcla todos los frutos secos y semillas en un recipiente pequeño.","Porciona con anticipación en bolsitas para evitar comer de más."],
    c:"Porcionar con anticipación evita comer directo de la bolsa grande, donde es fácil pasarse de cantidad." }
];
