// Recetario Premium Renacer™ — Cenas (36 recetas, ligeras, ideales 3+ horas antes de dormir)
module.exports = [
  { t:"Sopa de verduras con pollo deshebrado", f:"Fases 1-3",
    i:["1 taza de pollo cocido deshebrado","Zanahoria, calabaza y ejote picados","Caldo de pollo casero bajo en sodio","Cilantro al gusto"],
    p:["Cocina las verduras en el caldo hasta que suavicen.","Agrega el pollo deshebrado y calienta 5 minutos más.","Sirve caliente con cilantro fresco."],
    c:"Prepara el caldo casero sin cubos de consomé comerciales para controlar el sodio." },
  { t:"Crema de calabaza sin crema", f:"Fases 1-3",
    i:["2 tazas de calabaza en cubos","1/4 de cebolla","1 taza de leche de almendra sin azúcar","Nuez moscada al gusto"],
    p:["Cuece la calabaza y la cebolla en agua hasta suavizar.","Licúa con la leche de almendra hasta obtener textura cremosa.","Calienta de nuevo y sazona con nuez moscada."],
    c:"La leche de almendra sin azúcar da cremosidad sin la grasa saturada de la crema de leche." },
  { t:"Ensalada de espinaca, fresa y nuez", f:"Fases 2-3",
    i:["2 tazas de espinaca","5-6 fresas rebanadas","Un puño de nuez","Aceite de oliva y vinagre balsámico"],
    p:["Coloca la espinaca en un tazón grande.","Agrega las fresas y la nuez.","Sazona con aceite de oliva y vinagre balsámico."],
    c:"Ensalada ligera pero completa gracias a la grasa saludable de la nuez." },
  { t:"Sopa de lentejas ligera", f:"Fases 1-3",
    i:["1/2 taza de lentejas","Zanahoria y apio picados","Ajo, comino y cebolla"],
    p:["Sofríe cebolla y ajo con comino.","Agrega las lentejas, la zanahoria, el apio y agua o caldo.","Cocina 25 minutos hasta que las lentejas estén suaves."],
    c:"Versión más ligera que la de comida, con menos lenteja y más caldo." },
  { t:"Omelette de claras con verduras para cena", f:"Fases 1-3",
    i:["4 claras de huevo","1/2 taza de pimiento y champiñón picados","Sal y pimienta"],
    p:["Saltea las verduras hasta suavizar.","Agrega las claras batidas.","Cocina a fuego medio hasta cuajar y dobla el omelette."],
    c:"Las claras son más ligeras para digerir por la noche que el huevo entero." },
  { t:"Ensalada de nopales con queso panela", f:"Fases 1-3",
    i:["1 taza de nopal cocido","30 g de queso panela en cubos","Jitomate y cebolla morada","Orégano, limón y aceite de oliva"],
    p:["Mezcla el nopal con jitomate y cebolla.","Agrega el queso panela en cubos.","Sazona con orégano, limón y aceite de oliva."],
    c:"Enjuaga bien el nopal cocido para quitar el exceso de baba antes de mezclar." },
  { t:"Caldo de pollo con verduras", f:"Fases 1-3",
    i:["1 pechuga de pollo","Zanahoria, calabaza, apio y cebolla","Cilantro y limón para servir"],
    p:["Cocina la pechuga entera en agua con la cebolla hasta que esté bien cocida.","Deshebra el pollo y regrésalo al caldo junto con las verduras picadas.","Cocina 10 minutos más y sirve con cilantro y limón."],
    c:"Congela porciones individuales de este caldo para tener cenas listas entre semana." },
  { t:"Ensalada de atún y aguacate", f:"Fases 1-3",
    i:["1 lata de atún en agua","1/4 de aguacate","Pepino y jitomate picados","Limón y sal moderada"],
    p:["Escurre bien el atún.","Mezcla con pepino, jitomate y aguacate.","Sazona con limón y una pizca de sal."],
    c:"Cena ligera y rápida, ideal para noches con poco tiempo." },
  { t:"Sopa de brócoli y coliflor", f:"Fases 1-3",
    i:["1 taza de brócoli","1 taza de coliflor","1/4 de cebolla","Ajo y caldo de verduras"],
    p:["Cuece el brócoli, la coliflor, la cebolla y el ajo en el caldo.","Licúa hasta obtener una crema tersa.","Calienta de nuevo antes de servir."],
    c:"Puedes decorar con un chorrito de aceite de oliva y semillas de calabaza." },
  { t:"Yogur natural con nueces y canela para cena ligera", f:"Fases 1-3",
    i:["1 taza de yogur natural sin azúcar","Un puño de nuez","Canela al gusto"],
    p:["Coloca el yogur en un tazón.","Agrega la nuez picada.","Espolvorea canela y sirve."],
    c:"Útil en noches donde se busca algo muy ligero pero con proteína." },
  { t:"Ensalada de garbanzo y pepino", f:"Fases 1-3",
    i:["1 taza de garbanzo cocido","1 pepino en cubos","Jitomate cherry, aceite de oliva y limón"],
    p:["Mezcla garbanzo, pepino y jitomate cherry.","Sazona con aceite de oliva y limón.","Deja reposar 10 minutos antes de servir para que se integren los sabores."],
    c:"El garbanzo aporta proteína vegetal que ayuda a sostener el ayuno nocturno." },
  { t:"Verduras salteadas con tofu", f:"Fases 1-3",
    i:["200 g de tofu firme en cubos","Verduras mixtas (pimiento, brócoli, zanahoria)","Ajo, jengibre y un toque de aceite de ajonjolí"],
    p:["Saltea el tofu hasta dorar por todos lados.","Retira y saltea las verduras con ajo y jengibre.","Regresa el tofu, mezcla y sirve caliente."],
    c:"Presiona el tofu antes de cocinarlo para que absorba mejor el sabor y dore más fácil." },
  { t:"Sopa azteca ligera con tiras de tortilla horneada", f:"Fases 1-3",
    i:["1 jitomate, 1/4 de cebolla, 1 diente de ajo","Caldo de pollo casero","2 tortillas de maíz cortadas en tiras y horneadas","Aguacate y queso panela para servir"],
    p:["Licúa jitomate, cebolla y ajo, cuela y cocina en el caldo 10 minutos.","Hornea las tiras de tortilla hasta dorar (no fritas).","Sirve el caldo con las tiras, aguacate y queso panela."],
    c:"Hornear las tiras de tortilla en vez de freírlas elimina el aceite extra de la receta clásica." },
  { t:"Ensalada de pollo y verduras mixtas", f:"Fases 1-3",
    i:["100 g de pollo cocido en tiras","Lechuga, jitomate, pepino y zanahoria rallada","Aceite de oliva y limón"],
    p:["Mezcla todas las verduras en un tazón grande.","Agrega el pollo en tiras.","Sazona con aceite de oliva y limón al gusto."],
    c:"Aprovecha el pollo que sobró de la comida para armar esta cena en minutos." },
  { t:"Crema de champiñones sin crema", f:"Fases 1-3",
    i:["2 tazas de champiñón fileteado","1/4 de cebolla y 1 diente de ajo","1 taza de leche descremada o vegetal sin azúcar"],
    p:["Saltea champiñón, cebolla y ajo hasta que doren ligeramente.","Licúa con la leche hasta obtener consistencia cremosa.","Calienta de nuevo antes de servir, sazonando al gusto."],
    c:"Reserva algunos champiñones salteados enteros para decorar encima al servir." },
  { t:"Rollitos de pechuga de pavo con verduras", f:"Fases 1-3",
    i:["4 rebanadas de pechuga de pavo (bajo en sodio si es posible)","Zanahoria rallada, pepino en bastones y espinaca"],
    p:["Extiende cada rebanada de pavo.","Coloca zanahoria, pepino y espinaca en el centro.","Enrolla apretado y sirve como rollitos fríos."],
    c:"Cena rápida sin cocción, ideal para noches muy cansadas." },
  { t:"Ensalada caprese con jitomate y queso panela", f:"Fases 1-3",
    i:["2 jitomates grandes en rodajas","60 g de queso panela en rodajas","Albahaca fresca","Aceite de oliva y vinagre balsámico"],
    p:["Alterna las rodajas de jitomate y queso panela en un plato.","Agrega hojas de albahaca fresca.","Sazona con aceite de oliva y un toque de vinagre balsámico."],
    c:"El queso panela sustituye bien a la mozzarella tradicional con menos grasa." },
  { t:"Sopa de espinaca y poro", f:"Fases 1-3",
    i:["2 tazas de espinaca","1 poro fileteado","Caldo de verduras y ajo"],
    p:["Sofríe el poro y el ajo hasta suavizar.","Agrega la espinaca y el caldo, cocina 5 minutos.","Licúa hasta obtener una crema y calienta de nuevo."],
    c:"El poro aporta un sabor suave, menos fuerte que la cebolla, ideal para la cena." },
  { t:"Filete de pescado al vapor con verduras al vapor", f:"Fases 1-3",
    i:["200 g de filete de pescado blanco","Brócoli y zanahoria","Limón y hierbas frescas"],
    p:["Coloca el pescado y las verduras en la vaporera.","Cocina 10 minutos hasta que el pescado esté opaco y las verduras suaves.","Sirve con limón y hierbas frescas."],
    c:"Cena muy ligera, ideal para noches después de una comida fuerte al mediodía." },
  { t:"Ensalada de col morada con semillas", f:"Fases 1-3",
    i:["2 tazas de col morada rallada","2 cucharadas de semillas de girasol o calabaza","Aceite de oliva, limón y sal moderada"],
    p:["Coloca la col morada en un tazón.","Agrega las semillas.","Sazona con aceite de oliva, limón y sal moderada, deja reposar 5 minutos."],
    c:"Dejar reposar la col con el aderezo unos minutos la suaviza y mejora el sabor." },
  { t:"Caldo de verduras con huevo", f:"Fases 1-3",
    i:["Caldo de verduras casero","1 huevo por porción","Cilantro y limón"],
    p:["Calienta el caldo de verduras.","Casca el huevo directamente en el caldo hirviendo y cocina 3 minutos.","Sirve con cilantro y limón."],
    c:"El huevo se cocina directo en el caldo, sin necesidad de sartén adicional." },
  { t:"Wrap de lechuga con pollo y verduras", f:"Fases 1-3",
    i:["Hojas grandes de lechuga romana o italiana","100 g de pollo cocido en tiras","Zanahoria rallada y pepino en bastones"],
    p:["Usa cada hoja de lechuga como si fuera una tortilla.","Rellena con pollo, zanahoria y pepino.","Enrolla o dobla como taco y come de inmediato."],
    c:"Sustituye la tortilla por lechuga cuando quieras una cena baja en carbohidratos." },
  { t:"Ensalada de calabacita asada con queso feta", f:"Fases 1-3",
    i:["2 calabacitas en rodajas, asadas","30 g de queso feta desmoronado","Aceite de oliva y orégano"],
    p:["Asa las calabacitas en comal o parrilla hasta que doren.","Coloca en un plato y agrega el queso feta.","Sazona con aceite de oliva y orégano."],
    c:"Asar la calabacita concentra su sabor y la hace más satisfactoria a pesar de ser ligera." },
  { t:"Sopa fría de pepino (gazpacho ligero)", f:"Fases 1-3",
    i:["2 pepinos pelados","1/2 taza de yogur natural sin azúcar","Ajo, eneldo y limón"],
    p:["Licúa el pepino con el yogur, ajo, eneldo y limón.","Refrigera al menos 30 minutos.","Sirve frío, ideal para noches calurosas."],
    c:"Esta sopa no requiere cocción — perfecta para cuando hace mucho calor." },
  { t:"Tofu a la plancha con verduras salteadas", f:"Fases 1-3",
    i:["200 g de tofu firme en rebanadas","Verduras mixtas al gusto","Salsa de soya baja en sodio (con moderación)"],
    p:["Cocina el tofu a la plancha hasta dorar por ambos lados.","Saltea las verduras aparte.","Sirve juntos con un toque mínimo de salsa de soya baja en sodio."],
    c:"Usa la salsa de soya baja en sodio con moderación — sigue aportando sal." },
  { t:"Ensalada de espárragos y huevo cocido", f:"Fases 1-3",
    i:["1 taza de espárragos al vapor","2 huevos cocidos en rodajas","Aceite de oliva y limón"],
    p:["Cocina los espárragos al vapor hasta que estén suaves pero firmes.","Coloca en un plato con el huevo cocido en rodajas.","Sazona con aceite de oliva y limón."],
    c:"No sobrecuezas el espárrago, pierde textura y color si se pasa de tiempo." },
  { t:"Crema de zanahoria y jengibre", f:"Fases 1-3",
    i:["3 zanahorias en trozos","1 cucharadita de jengibre rallado","Caldo de verduras"],
    p:["Cuece las zanahorias en el caldo hasta suavizar.","Licúa con el jengibre hasta obtener consistencia cremosa.","Calienta de nuevo y sirve."],
    c:"El jengibre le da un toque digestivo agradable para la cena." },
  { t:"Ensalada de nopal, jitomate y cebolla morada", f:"Fases 1-3",
    i:["1 taza de nopal cocido","1 jitomate picado","1/4 de cebolla morada","Orégano, limón y aceite de oliva"],
    p:["Mezcla el nopal, jitomate y cebolla en un tazón.","Sazona con orégano, limón y aceite de oliva.","Deja reposar 5-10 minutos antes de servir."],
    c:"Ensalada clásica mexicana, ligera y rica en fibra." },
  { t:"Sopa de chícharo ligera", f:"Fases 1-3",
    i:["1 taza de chícharo (guisante)","1/4 de cebolla y ajo","Caldo de verduras y hierbabuena"],
    p:["Sofríe la cebolla y el ajo.","Agrega el chícharo y el caldo, cocina 10 minutos.","Licúa con un poco de hierbabuena y sirve."],
    c:"La hierbabuena le da frescura a esta sopa de sabor suave." },
  { t:"Rollitos de pepino rellenos de atún", f:"Fases 1-3",
    i:["1 pepino grande en rebanadas longitudinales delgadas","1 lata de atún en agua","Yogur natural y eneldo"],
    p:["Mezcla el atún escurrido con un poco de yogur y eneldo.","Coloca la mezcla sobre cada rebanada de pepino.","Enrolla y asegura con un palillo si es necesario."],
    c:"Cena ligera y fresca, sin necesidad de cocinar nada." },
  { t:"Ensalada de brócoli al vapor con almendras", f:"Fases 1-3",
    i:["2 tazas de brócoli al vapor","Almendra fileteada","Aceite de oliva y limón"],
    p:["Cocina el brócoli al vapor hasta que esté suave pero firme.","Coloca en un plato y agrega la almendra fileteada.","Sazona con aceite de oliva y limón."],
    c:"Sirve tibio o frío, ambas versiones son agradables." },
  { t:"Caldo de pollo con verduras y arroz integral", f:"Fases 2-3 — porción pequeña de arroz",
    i:["Caldo de pollo casero con pollo deshebrado","Zanahoria y calabaza","2-3 cucharadas de arroz integral cocido"],
    p:["Calienta el caldo con las verduras picadas.","Agrega el pollo deshebrado.","Sirve con una pequeña porción de arroz integral dentro del caldo."],
    c:"La porción de arroz debe ser pequeña por la noche, incluso siendo integral." },
  { t:"Ensalada de jícama y pepino con limón", f:"Fases 1-3",
    i:["1 taza de jícama en bastones","1 pepino en bastones","Limón y chile piquín al gusto (sin azúcar)"],
    p:["Mezcla la jícama y el pepino en un tazón.","Exprime limón encima.","Espolvorea chile piquín sin azúcar añadida."],
    c:"Refrescante y muy baja en calorías, ideal para acompañar otra proteína ligera." },
  { t:"Verduras al vapor con salsa de yogur y eneldo", f:"Fases 1-3",
    i:["Verduras mixtas al vapor (brócoli, zanahoria, coliflor)","1/2 taza de yogur natural sin azúcar","Eneldo y limón"],
    p:["Cocina las verduras al vapor hasta que estén suaves.","Mezcla el yogur con eneldo y limón para la salsa.","Sirve las verduras bañadas con la salsa."],
    c:"El yogur con hierbas es una alternativa ligera a las salsas cremosas tradicionales." },
  { t:"Sopa de jitomate asado", f:"Fases 1-3",
    i:["4 jitomates asados","1/4 de cebolla y ajo asados","Caldo de verduras y albahaca"],
    p:["Asa jitomate, cebolla y ajo hasta que se doren ligeramente.","Licúa con el caldo de verduras.","Calienta y sirve con albahaca fresca."],
    c:"Asar los ingredientes antes de licuar da un sabor más profundo sin necesidad de más sal." },
  { t:"Ensalada mixta con huevo cocido y aguacate", f:"Fases 1-3",
    i:["Lechuga, jitomate y pepino","2 huevos cocidos en rodajas","1/4 de aguacate"],
    p:["Arma la ensalada con la lechuga, jitomate y pepino.","Agrega el huevo cocido en rodajas.","Corona con el aguacate en cubos."],
    c:"Cena completa, sencilla y sin necesidad de estufa si el huevo ya está cocido con anticipación." }
];
